version: 0.0.1

server:
  port: 8080

spring:
  application:
    name: Shop Application
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      fail-on-empty-beans: false

token:
  signing:
    key: 53a73e5f1c4e0a2d3b5f2d784E6a1b423d6d247d1f6e5c3a596d635a75327855

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/swagger-ui-custom.html