server:
  port: 0

spring:
  application:
    name: integration-test
  main:
    banner-mode: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false